In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import json

In [4]:
##FFmpg (turns your gource into a MP4)
#brew install ffmpeg

In [5]:
##when that is finished installing type 
#brew install gource

**Run this with**:
- gource custom.log --seconds-per-day 1 --bloom-intensity 0.3
- gource custom.log --seconds-per-day 1 --bloom-intensity 0.3 -e 0.2 -i 120
- gource custom.log --seconds-per-day 1 --bloom-intensity 0.3 -e 0.2 -i 120 --title "Development of the amount of characters in Rick and Morty"
- gource custom.log --seconds-per-day 1 -1440x900 --bloom-intensity 0.1 -e 0.2 -i 120 --title "Development of the amount of characters in Rick and Morty"
- gource custom.log -1280x720 --seconds-per-day 2 --key --hide filenames

**Output video**:
- gource custom.log -1280x720 --seconds-per-day 2 --key --hide dirnames, -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -crf 1 -threads 0 -bf 0 output.mp4

- link : [custom log format](https://github.com/acaudwell/Gource/wiki/Custom-Log-Format)
- link : [visualization](https://edgeryders.eu/t/visualizing-our-7-years-of-online-dialogue-with-gource/11905)
- likn : [stuff to gource](https://leonjza.github.io/blog/2013/07/27/stuff-to-gource./#get-the-code-setup-your-own)

The software to create this is Gource 2, an open source tool originally meant to visualize Git repositories. Fortunately it also can read a custom log format 9.

For Discourse, the custom log file would be a text file with each line containing the following components, delimited by `|`:

- timestamp
- username
- type of action (Added, Modified, Deleted); the “M” is useful esp. for wikis
- path to the affected resource. Usually this applies to files, but in our case it would be about posts. This is the part we’d have to adapt to Discourse. Our path format could be `category/subcategory/topic-id/post-id` or it could even include the full threading information with any depth of nesting, such as `category/subcategory/topic-id/parent-post-id/parent-post-id/post-id`
- color for the affected resource (optional); this could be chosen according to the category color on edgeryders.eu

Example line:

- `1275543595|matthias|A|earthos/reef/1234/1`

In [2]:
import pandas as pd
import pandasql as ps
import numpy as np
import re
import tqdm
from tqdm import tqdm
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [4]:
df_characters = pd.read_csv('../df_characters.csv')
df_episodes = pd.read_csv('../df_episodes.csv')
df_transcripts = pd.read_csv('../df_transcripts.csv')

In [5]:
from ast import literal_eval
df_characters['episode'] = df_characters['episode'].apply(literal_eval)

In [6]:
df_characters_exploded = df_characters.explode('episode')

In [7]:
df_characters_exploded.episode = df_characters_exploded.episode.astype(int)

In [12]:
df_characters_exploded

,name,status,species,type,gender,origin,location,image,episode,url,created,references
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,1,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,2,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,3,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,4,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,5,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
821,Young Jerry,unknown,Human,NaN,Male,Earth (Unknown dimension),Earth (Unknown dimension),https://rickandmortyapi.com/api/character/avat...,51,https://rickandmortyapi.com/api/character/822,2021-11-02T17:18:31.934Z,NaN
822,Young Beth,unknown,Human,NaN,Female,Earth (Unknown dimension),Earth (Unknown dimension),https://rickandmortyapi.com/api/character/avat...,51,https://rickandmortyapi.com/api/character/823,2021-11-02T17:19:00.951Z,NaN
823,Young Beth,unknown,Human,NaN,Female,Earth (Unknown dimension),Earth (Unknown dimension),https://rickandmortyapi.com/api/character/avat...,51,https://rickandmortyapi.com/api/character/824,2021-11-02T17:19:47.957Z,NaN
824,Young Jerry,unknown,Human,NaN,Male,Earth (Unknown dimension),Earth (Unknown dimension),https://rickandmortyapi.com/api/character/avat...,51,https://rickandmortyapi.com/api/character/825,2021-11-02T17:20:14.305Z,NaN
825,Butter Robot,Alive,Robot,Passing Butter Robot,Genderless,Earth (Replacement Dimension),Earth (Replacement Dimension),https://rickandmortyapi.com/api/character/avat...,9,https://rickandmortyapi.com/api/character/826,2021-11-02T17:24:37.458Z,NaN

In [8]:
import datetime
from datetime import datetime
from datetime import timedelta
import time

In [9]:
date_range = pd.date_range(datetime.today() - timedelta(days=51), periods=51)
date_series = pd.Series(date_range)
df_episode_unix_timestamp = pd.DataFrame(pd.DataFrame(date_series).values[::-1])\
    .reset_index(drop=False)\
    .rename(columns={'index':'episode', 0:'timestamp'})
df_episode_unix_timestamp['episode'] = df_episode_unix_timestamp['episode'].apply(lambda x: x+1)
df_episode_unix_timestamp['unixtime'] = df_episode_unix_timestamp['timestamp'].astype(int)
df_episode_unix_timestamp

    episode                  timestamp             unixtime
0         1 2021-11-29 17:21:37.393343  1638206497393343000
1         2 2021-11-28 17:21:37.393343  1638120097393343000
2         3 2021-11-27 17:21:37.393343  1638033697393343000
3         4 2021-11-26 17:21:37.393343  1637947297393343000
4         5 2021-11-25 17:21:37.393343  1637860897393343000
5         6 2021-11-24 17:21:37.393343  1637774497393343000
6         7 2021-11-23 17:21:37.393343  1637688097393343000
7         8 2021-11-22 17:21:37.393343  1637601697393343000
8         9 2021-11-21 17:21:37.393343  1637515297393343000
9        10 2021-11-20 17:21:37.393343  1637428897393343000
10       11 2021-11-19 17:21:37.393343  1637342497393343000
11       12 2021-11-18 17:21:37.393343  1637256097393343000
12       13 2021-11-17 17:21:37.393343  1637169697393343000
13       14 2021-11-16 17:21:37.393343  1637083297393343000
14       15 2021-11-15 17:21:37.393343  1636996897393343000
15       16 2021-11-14 17:21:37.393343  1636910497393343000
16       17 2021-11-13 17:21:37.393343  1636824097393343000
17       18 2021-11-12 17:21:37.393343  1636737697393343000
18       19 2021-11-11 17:21:37.393343  1636651297393343000
19       20 2021-11-10 17:21:37.393343  1636564897393343000
20       21 2021-11-09 17:21:37.393343  1636478497393343000
21       22 2021-11-08 17:21:37.393343  1636392097393343000
22       23 2021-11-07 17:21:37.393343  1636305697393343000
23       24 2021-11-06 17:21:37.393343  1636219297393343000
24       25 2021-11-05 17:21:37.393343  1636132897393343000
25       26 2021-11-04 17:21:37.393343  1636046497393343000
26       27 2021-11-03 17:21:37.393343  1635960097393343000
27       28 2021-11-02 17:21:37.393343  1635873697393343000
28       29 2021-11-01 17:21:37.393343  1635787297393343000
29       30 2021-10-31 17:21:37.393343  1635700897393343000
30       31 2021-10-30 17:21:37.393343  1635614497393343000
31       32 2021-10-29 17:21:37.393343  1635528097393343000
32       33 2021-10-28 17:21:37.393343  1635441697393343000
33       34 2021-10-27 17:21:37.393343  1635355297393343000
34       35 2021-10-26 17:21:37.393343  1635268897393343000
35       36 2021-10-25 17:21:37.393343  1635182497393343000
36       37 2021-10-24 17:21:37.393343  1635096097393343000
37       38 2021-10-23 17:21:37.393343  1635009697393343000
38       39 2021-10-22 17:21:37.393343  1634923297393343000
39       40 2021-10-21 17:21:37.393343  1634836897393343000
40       41 2021-10-20 17:21:37.393343  1634750497393343000
41       42 2021-10-19 17:21:37.393343  1634664097393343000
42       43 2021-10-18 17:21:37.393343  1634577697393343000
43       44 2021-10-17 17:21:37.393343  1634491297393343000
44       45 2021-10-16 17:21:37.393343  1634404897393343000
45       46 2021-10-15 17:21:37.393343  1634318497393343000
46       47 2021-10-14 17:21:37.393343  1634232097393343000
47       48 2021-10-13 17:21:37.393343  1634145697393343000
48       49 2021-10-12 17:21:37.393343  1634059297393343000
49       50 2021-10-11 17:21:37.393343  1633972897393343000
50       51 2021-10-10 17:21:37.393343  1633886497393343000

In [193]:
date_range = pd.date_range(datetime.today() - timedelta(days=51), periods=51)
date_series = pd.Series(date_range)
df_episode_unix_timestamp = pd.DataFrame(pd.DataFrame(date_series))\
    .reset_index(drop=False)\
    .rename(columns={'index':'episode', 0:'timestamp'})
df_episode_unix_timestamp['episode'] = df_episode_unix_timestamp['episode'].apply(lambda x: x+1)
df_episode_unix_timestamp['unixtime'] = df_episode_unix_timestamp['timestamp'].astype(int)
df_episode_unix_timestamp['unixtime'] = (df_episode_unix_timestamp.timestamp - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')

In [194]:
df_episode_unix_timestamp

    episode                  timestamp    unixtime
0         1 2021-10-04 15:13:11.890278  1633360391
1         2 2021-10-05 15:13:11.890278  1633446791
2         3 2021-10-06 15:13:11.890278  1633533191
3         4 2021-10-07 15:13:11.890278  1633619591
4         5 2021-10-08 15:13:11.890278  1633705991
5         6 2021-10-09 15:13:11.890278  1633792391
6         7 2021-10-10 15:13:11.890278  1633878791
7         8 2021-10-11 15:13:11.890278  1633965191
8         9 2021-10-12 15:13:11.890278  1634051591
9        10 2021-10-13 15:13:11.890278  1634137991
10       11 2021-10-14 15:13:11.890278  1634224391
11       12 2021-10-15 15:13:11.890278  1634310791
12       13 2021-10-16 15:13:11.890278  1634397191
13       14 2021-10-17 15:13:11.890278  1634483591
14       15 2021-10-18 15:13:11.890278  1634569991
15       16 2021-10-19 15:13:11.890278  1634656391
16       17 2021-10-20 15:13:11.890278  1634742791
17       18 2021-10-21 15:13:11.890278  1634829191
18       19 2021-10-22 15:13:11.890278  1634915591
19       20 2021-10-23 15:13:11.890278  1635001991
20       21 2021-10-24 15:13:11.890278  1635088391
21       22 2021-10-25 15:13:11.890278  1635174791
22       23 2021-10-26 15:13:11.890278  1635261191
23       24 2021-10-27 15:13:11.890278  1635347591
24       25 2021-10-28 15:13:11.890278  1635433991
25       26 2021-10-29 15:13:11.890278  1635520391
26       27 2021-10-30 15:13:11.890278  1635606791
27       28 2021-10-31 15:13:11.890278  1635693191
28       29 2021-11-01 15:13:11.890278  1635779591
29       30 2021-11-02 15:13:11.890278  1635865991
30       31 2021-11-03 15:13:11.890278  1635952391
31       32 2021-11-04 15:13:11.890278  1636038791
32       33 2021-11-05 15:13:11.890278  1636125191
33       34 2021-11-06 15:13:11.890278  1636211591
34       35 2021-11-07 15:13:11.890278  1636297991
35       36 2021-11-08 15:13:11.890278  1636384391
36       37 2021-11-09 15:13:11.890278  1636470791
37       38 2021-11-10 15:13:11.890278  1636557191
38       39 2021-11-11 15:13:11.890278  1636643591
39       40 2021-11-12 15:13:11.890278  1636729991
40       41 2021-11-13 15:13:11.890278  1636816391
41       42 2021-11-14 15:13:11.890278  1636902791
42       43 2021-11-15 15:13:11.890278  1636989191
43       44 2021-11-16 15:13:11.890278  1637075591
44       45 2021-11-17 15:13:11.890278  1637161991
45       46 2021-11-18 15:13:11.890278  1637248391
46       47 2021-11-19 15:13:11.890278  1637334791
47       48 2021-11-20 15:13:11.890278  1637421191
48       49 2021-11-21 15:13:11.890278  1637507591
49       50 2021-11-22 15:13:11.890278  1637593991
50       51 2021-11-23 15:13:11.890278  1637680391

The software to create this is Gource 2, an open source tool originally meant to visualize Git repositories. Fortunately it also can read a custom log format 9.

For Discourse, the custom log file would be a text file with each line containing the following components, delimited by `|`:

- timestamp
- username
- type of action (Added, Modified, Deleted); the “M” is useful esp. for wikis
- path to the affected resource. Usually this applies to files, but in our case it would be about posts. This is the part we’d have to adapt to Discourse. Our path format could be `category/subcategory/topic-id/post-id` or it could even include the full threading information with any depth of nesting, such as `category/subcategory/topic-id/parent-post-id/parent-post-id/post-id`
- color for the affected resource (optional); this could be chosen according to the category color on edgeryders.eu

Example line:

- `1275543595|matthias|A|earthos/reef/1234/1`

In [15]:
df_characters_exploded

,name,status,species,type,gender,origin,location,image,episode,url,created,references
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,1,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,2,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,3,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,4,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
0,Rick Sanchez,Alive,Human,NaN,Male,Earth (C-137),Citadel of Ricks,https://rickandmortyapi.com/api/character/avat...,5,https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z,"['Morty Smith', 'Summer Smith', 'Beth Smith', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
821,Young Jerry,unknown,Human,NaN,Male,Earth (Unknown dimension),Earth (Unknown dimension),https://rickandmortyapi.com/api/character/avat...,51,https://rickandmortyapi.com/api/character/822,2021-11-02T17:18:31.934Z,NaN
822,Young Beth,unknown,Human,NaN,Female,Earth (Unknown dimension),Earth (Unknown dimension),https://rickandmortyapi.com/api/character/avat...,51,https://rickandmortyapi.com/api/character/823,2021-11-02T17:19:00.951Z,NaN
823,Young Beth,unknown,Human,NaN,Female,Earth (Unknown dimension),Earth (Unknown dimension),https://rickandmortyapi.com/api/character/avat...,51,https://rickandmortyapi.com/api/character/824,2021-11-02T17:19:47.957Z,NaN
824,Young Jerry,unknown,Human,NaN,Male,Earth (Unknown dimension),Earth (Unknown dimension),https://rickandmortyapi.com/api/character/avat...,51,https://rickandmortyapi.com/api/character/825,2021-11-02T17:20:14.305Z,NaN
825,Butter Robot,Alive,Robot,Passing Butter Robot,Genderless,Earth (Replacement Dimension),Earth (Replacement Dimension),https://rickandmortyapi.com/api/character/avat...,9,https://rickandmortyapi.com/api/character/826,2021-11-02T17:24:37.458Z,NaN

# Character pr. episode (custom_char_episode.log)

- 1633360391|episode_1|A|episode_1/rick/rick.cpp
- 1633360391|episode_1|A|episode_1/morty/rick.cpp
- 1633360391|episode_1|A|episode_1/summer/rick.cpp
- 1633360391|episode_2|A|episode_2/rick.cpp
- 1633360391|episode_3|A|episode_3/rick.cpp

In [31]:
res = ps.sqldf(
    """
    select 
        1633360391 || '|' || 'episode_' || episode || '|' || 'A' || '|' || 'episode_' || episode || '/' || character || '/' || 'player.cpp' as output
    from
    
    (
    
    select 
       episode
    ,  character
    from 
        (

        select
              replace(df.name, ' ', '_') as character
            , df.episode
        from df_characters_exploded df
        order by df.episode asc
        )
    order by episode asc
    )
    """
)

res

                                                 output
0     1633360391|episode_1|A|episode_1/Rick_Sanchez/...
1     1633360391|episode_1|A|episode_1/Morty_Smith/p...
2     1633360391|episode_1|A|episode_1/Bepisian/play...
3     1633360391|episode_1|A|episode_1/Beth_Smith/pl...
4     1633360391|episode_1|A|episode_1/Canklanker_Th...
...                                                 ...
1262  1633360391|episode_51|A|episode_51/Redhead_Mor...
1263  1633360391|episode_51|A|episode_51/Young_Jerry...
1264  1633360391|episode_51|A|episode_51/Young_Beth/...
1265  1633360391|episode_51|A|episode_51/Young_Beth/...
1266  1633360391|episode_51|A|episode_51/Young_Jerry...

[1267 rows x 1 columns]

In [32]:
with open('custom_char_episode.log', 'w') as f:
    for row in res.output:
        #print(row)
        f.write(row + '\n')

# Something Else

In [195]:
ps.sqldf(
    """
    select
          replace(df.name, ' ', '_') as character
        , df.episode
        , ts.timestamp
        , ts.unixtime
    from df_characters_exploded df
    inner join df_episode_unix_timestamp as ts
        on ts.episode = df.episode
    order by df.episode asc
    """
)

            character  episode                   timestamp    unixtime
0        Rick_Sanchez        1  2021-10-04 15:13:11.890278  1633360391
1         Morty_Smith        1  2021-10-04 15:13:11.890278  1633360391
2            Bepisian        1  2021-10-04 15:13:11.890278  1633360391
3          Beth_Smith        1  2021-10-04 15:13:11.890278  1633360391
4     Canklanker_Thom        1  2021-10-04 15:13:11.890278  1633360391
...               ...      ...                         ...         ...
1262    Redhead_Morty       51  2021-11-23 15:13:11.890278  1637680391
1263      Young_Jerry       51  2021-11-23 15:13:11.890278  1637680391
1264       Young_Beth       51  2021-11-23 15:13:11.890278  1637680391
1265       Young_Beth       51  2021-11-23 15:13:11.890278  1637680391
1266      Young_Jerry       51  2021-11-23 15:13:11.890278  1637680391

[1267 rows x 4 columns]

`unixtime || '|' || character || '|' || 'A' || '|' || 'episodes/episode_nr/' || episode || '.txt' as output`

In [214]:
# which characters touch which episode
res = ps.sqldf(
    """
    select 
        unixtime || '|' || character || '|' || 'A' || '|' || episode || '.txt' as output
    from
    
    (
    
    select 
       episode
    ,  character
    ,  unixtime
    from 
        (

        select
              replace(df.name, ' ', '_') as character
            , df.episode
            , ts.timestamp
            , ts.unixtime
        from df_characters_exploded df
        inner join df_episode_unix_timestamp as ts
            on ts.episode = df.episode
        order by df.episode asc
        )
    order by episode asc
    )
    """
)
res

                                  output
0        1633360391|Rick_Sanchez|A|1.txt
1         1633360391|Morty_Smith|A|1.txt
2            1633360391|Bepisian|A|1.txt
3          1633360391|Beth_Smith|A|1.txt
4     1633360391|Canklanker_Thom|A|1.txt
...                                  ...
1262   1637680391|Redhead_Morty|A|51.txt
1263     1637680391|Young_Jerry|A|51.txt
1264      1637680391|Young_Beth|A|51.txt
1265      1637680391|Young_Beth|A|51.txt
1266     1637680391|Young_Jerry|A|51.txt

[1267 rows x 1 columns]

In [215]:
#res = ps.sqldf(
#    """
#    
#    select 
#       unixtime || '|' || character || '|' || 'A' || '|' || 'episodes/episode_nr/' || episode || '.txt' as output
#    from 
#    (
#
#    select
#          replace(df.name, ' ', '_') as character
#        , df.episode
#        , ts.timestamp
#        , ts.unixtime
#    from df_characters_exploded df
#    inner join df_episode_unix_timestamp as ts
#        on ts.episode = df.episode
#    )
#    order by 1 desc
#    """
#)

In [219]:
with open('custom.log', 'w') as f:
    for row in res.output:
        #print(row)
        f.write(row + '\n')

- gource --hide dirnames,filenames --seconds-per-day 0.1 --auto-skip-seconds 1 -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.mp4

In [223]:
# which episodes that touch the characters
res = ps.sqldf(
    """
    select 
        unixtime || '|' || episode || '|' || 'A' || '|' || character || '.txt' as output
    from
    
    (
    
    select 
       episode
    ,  character
    ,  unixtime
    from 
        (

        select
              replace(df.name, ' ', '_') as character
            , df.episode
            , ts.timestamp
            , ts.unixtime
        from df_characters_exploded df
        inner join df_episode_unix_timestamp as ts
            on ts.episode = df.episode
        order by df.episode asc
        )
    order by episode asc
    )
    """
)
res

                                  output
0        1633360391|1|A|Rick_Sanchez.txt
1         1633360391|1|A|Morty_Smith.txt
2            1633360391|1|A|Bepisian.txt
3          1633360391|1|A|Beth_Smith.txt
4     1633360391|1|A|Canklanker_Thom.txt
...                                  ...
1262   1637680391|51|A|Redhead_Morty.txt
1263     1637680391|51|A|Young_Jerry.txt
1264      1637680391|51|A|Young_Beth.txt
1265      1637680391|51|A|Young_Beth.txt
1266     1637680391|51|A|Young_Jerry.txt

[1267 rows x 1 columns]

In [224]:
# something
res = ps.sqldf(
    """
    select 
        unixtime || '|' || episode || '|' || 'A' || '|' || character || '/' || episode || '.txt' as output
    from
    
    (
    
    select 
       episode
    ,  character
    ,  unixtime
    from 
        (

        select
              replace(df.name, ' ', '_') as character
            , df.episode
            , ts.timestamp
            , ts.unixtime
        from df_characters_exploded df
        inner join df_episode_unix_timestamp as ts
            on ts.episode = df.episode
        order by df.episode asc
        )
    order by episode asc
    )
    """
)
res

                                    output
0        1633360391|1|A|Rick_Sanchez/1.txt
1         1633360391|1|A|Morty_Smith/1.txt
2            1633360391|1|A|Bepisian/1.txt
3          1633360391|1|A|Beth_Smith/1.txt
4     1633360391|1|A|Canklanker_Thom/1.txt
...                                    ...
1262  1637680391|51|A|Redhead_Morty/51.txt
1263    1637680391|51|A|Young_Jerry/51.txt
1264     1637680391|51|A|Young_Beth/51.txt
1265     1637680391|51|A|Young_Beth/51.txt
1266    1637680391|51|A|Young_Jerry/51.txt

[1267 rows x 1 columns]